### PR TITLE
Update default apache tools

### PR DESCRIPTION
**Pull request by paulsheldrake**
Make sure rewrite and headers modules are enabled so pretty URLs work out of the box.

Install the minimum PHP tools so wordpress status doesn't flag missing dependencies

### CODE REVIEW

**Comment by q0rban** [comment]
test this please

**Comment by q0rban** [comment]
test this please

**Comment by q0rban** [comment]
test this please

**Comment by q0rban** [comment]
test this please

**Comment by q0rban** [comment]
This is great, thanks @paulsheldrake . Is the addition of imagemagick a dependency / requirement for wordpress? If not, I'd like to remove those lines.

**Comment by paulsheldrake** [comment]
It's something that's flagged in the  WordPress status report.  Depending
on the site it might cause issues if it's missing and they do a lot of
image operations
https://make.wordpress.org/hosting/handbook/handbook/server-environment/#php-extensions

**Pull request merged**
