### PR TITLE
Add Twitter cards to documentation site

### PR DESCRIPTION
**Pull request by dacharyc**
This needs a bit of testing before it's ready to merge, but hopefully it will add Twitter cards to the documentation site.

### CODE REVIEW

**Comment by dacharyc** [comment]
The Twitter Card Validator appears to be picking up the metadata I've added for our new Twitter card functionality for the documentation site, but is not displaying an image in the card. I verified that the image path is correct in the Tugboat Preview, so I'm wondering if this is some sort of unexpected artifact of this being a Tugboat Preview? Or if it's something wrong with the code and is not calling the image properly?

Could use a second set of eyes @q0rban and/or @bchavet .

Screen Shot 2020-04-27 at 10 18 22 AM

**Comment by dacharyc** [comment]
Now the Twitter card validator is "Unable to render Card preview" from a Tugboat Preview, but the metadata on the page looks right. How do people feel about merging this and hoping Twitter can render cards properly after this is merged? The only thing I'm uncertain about is how the image will display, but we can always tweak that after it's live without impacting viewers of the docs site. Thoughts @bchavet @q0rban ?

**Comment by bchavet** [comment]
Looks like it doesn't like the relative URL

Screen Shot 2020-04-30 at 12 19 02 AM

I manually changed that meta tag to an absolute URL, and this is what came up.

Screen Shot 2020-04-30 at 12 20 53 AM

I imagine we will have the same problem if the full URL is not present when we deploy to production. Maybe the way to deploy this is to push the image to production in a separate PR, so we have a live, production link to explicitly set for the twitter card.

**Comment by dacharyc** [comment]
That did the trick, @bchavet , thank you!

So I didn't like the image that I had (a screenshot of the documentation site) - long story short, I've switched it to the new logo and it looks pretty sharp.

Screen Shot 2020-04-30 at 10 04 54 AM

I put together another commit on a sub-branch (https://github.com/TugboatQA/docs/tree/social-card-page-override) to test the functionality of overriding the master Twitter card config with page-specific front matter. Used a random image that was already live on production just to test. That works; here's how it displays (ignore the image sizing - it's not the right aspect ratio for this):

Screen Shot 2020-04-30 at 10 20 50 AM

So I think this is working now and this PR is ready for review/merging.

**Pull request merged**
