### PR TITLE
fix: use minor versions of PHP in all example configs

### PR DESCRIPTION
**Pull request by q0rban**

### CODE REVIEW

**Comment by rabbitlair** [comment]
Can I suggest we reference PHP 8.2 instead of 8.1? Asking because 8.1 end of active support will be in a couple of months, next November 25th, 2023. Not a big deal.

**Review by rabbitlair — APPROVED** [review]

**Comment by q0rban** [comment]
> Can I suggest we reference PHP 8.2 instead of 8.1? Asking because 8.1 end of active support will be in a couple of months, next November 25th, 2023. Not a big deal.

That's a good point that I hadn't considered. The reason I chose 8.1 is because that is the only version of PHP that is supported by all modern versions of Drupal at https://www.drupal.org/docs/getting-started/system-requirements/php-requirements:

Screen Shot 2023-09-13 at 9 21 40 AM

**Comment by q0rban** [comment]
Unless I'm misreading something, It seems like 8.1 will be supported until 25 Nov 2024, is that right?

https://www.php.net/supported-versions.php

**Comment by rabbitlair** [comment]
> Unless I'm misreading something, It seems like 8.1 will be supported until 25 Nov 2024, is that right?

Well, active support ends 25 Nov 2023, and extended support one year later. Ok, let's go with 8.1, I was being a little too nit picky with this one :sweat_smile:

**Pull request merged**
