### PR TITLE
Update Tugboat avatar in bot account documentation

### PR DESCRIPTION
**Pull request by q0rban**

### CODE REVIEW

**Comment by q0rban** [comment]
@dacharyc this was something we ran into with a client.

**Review by dacharyc — DISMISSED** [review]
Sorry, @q0rban , I had missed this when you made the PR. Sorry for the delay; thanks for bumping it!

**Comment by dacharyc** [comment]
test this please

**Comment by dacharyc** [comment]
@bchavet Looks like the Coding Standards check is failing, and I _think_ this is the relevant output from the log in Jenkins:

`+ docker run --rm -i -v /var/lib/****/workspace/Website__docs.tugboat.qa_Coding_Standards:/data -w /data node:10 yarn lint
yarn run v1.22.4
$ prettier --list-different "**/*.md"
content/administer-tugboat-crew/add-tugboat-bot-to-team.md
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Build step 'Execute shell' marked build as failure
Setting status of 1832231a421a6f3beb2ba154d7d995b5a2b2d2bb to FAILURE with url`

A little Googling hints to me that maybe there's a yarn version issue? But I'm not sure what to do from here.

This PR looks fine to me; is there any objection to doing an admin merge in spite of the coding standards failure?

**Comment by q0rban** [comment]
Wow, that was not a helpful linting error, is it?

Fixed with `$ yarn lint --write`

**Pull request merged**
