### PR TITLE
Remove .htaccess, let the apache config handle that

### PR DESCRIPTION
**Pull request by bchavet**

### CODE REVIEW

**Comment by q0rban** [comment]
I guess the drawbacks to this are that

1. We can't modify redirects within this repo
2. Redirects aren't testable on Tugboat

**Comment by bchavet** [comment]
If someone wants to host a copy of the documentation, there's no need for them to have a history of all the redirects. That is really only relevant to docs.tugboat.qa, and the apache vhost config is really the right place to manage that.

**Comment by bchavet** [comment]
test this please

**Comment by bchavet** [comment]
Sorry, I didn't do a very good job of explaining this.

Putting rewrites in .htaccess means that we have to make a number of assumptions around absolute vs relative paths. In order for us to use that .htaccess file for production, that means these assumptions would need to be specifically for docs.tugboat.qa. At that point, the information in the file is no longer about the repo, but for a specific deployment of the repo.

That aside, it's still best practice to manage redirects like this in the apache vhost config. They are easier to maintain there, and there is a performance benefit.

**Comment by q0rban** [comment]
> They are easier to maintain there, and there is a performance benefit.

Because I know you can take it, I'm going to disagree with you on both points here. :neckbeard: 

First, while it might be easier for *you* to maintain redirects in the vhost, it's not easier for others. 
Second, if you include the .htaccess in the vhost, it's no performance loss. 

```
AllowOverride None
Include /var/www/docs.tugboat.qa/.htaccess
```

**Comment by bchavet** [comment]
```
AllowOverride None
Include /var/www/docs.tugboat.qa/.htaccess
```

Fair point.

**Pull request merged**
