### PR TITLE
Fix a few broken links to Custom Environment Variables

### PR DESCRIPTION
**Pull request by q0rban**

### CODE REVIEW

**Comment by bchavet** [comment]
test this please

**Comment by bchavet** [comment]
test this please

**Comment by dacharyc** [comment]
> This seems like this set of links is meant to be a table of contents for this page. Linking to another page from here breaks that pattern. Thoughts @dacharyc ?

Yeah, that's the paradigm. I'd prefer to separate links to other pages - maybe in a brief writeup ala "Looking for information on how to set up custom environment variables? See Create [Custom Environment Variables]()."

Or, we could do it as a callout if that seems to make more sense.

**Comment by q0rban** [comment]
I do think it’s useful to have these two pages connected somehow, since often folks search for how to add custom environment variables and end up on the page that describes the Tugboat ones. I’ve done this a bunch myself.

**Comment by dacharyc** [comment]
How's this @q0rban ?

**Pull request merged**
