### PR TITLE
Add missing parenthesis/parentheses.

### PR DESCRIPTION
**Pull request by YesCT**

### CODE REVIEW

**Comment by q0rban** [comment]
Nice catch, thanks @YesCT ! 

I'm wondering if maybe this is an incomplete sentence too?

**Comment by dacharyc** [comment]
Oof, looks like that's roughly where the linter cuts things off, so I'm guessing something got moved around by the linter and removed somehow. I'm not sure what it should be but I'll add a couple of words to complete the sentence. Thanks for the catch, @YesCT and @q0rban !

**Comment by dacharyc** [comment]
test this please

**Comment by dacharyc** [comment]
Blarg. I did a silly so I'll close this and merge the version from my local. Thanks, both!

**Pull request closed without merging**
